# for devcontainer
services:
  node_app: # fixme
    build:
      target: devcontainers
      context: ./node_app # fixme
      dockerfile: Dockerfile
    image: node_app_devcontainer:latest
    container_name: node_app_devcontainer # fixme
    volumes:
      - ./:/app
